const protocols = [
  {
    id: 1,
    slug: "http",
    name: "HTTP / HTTPS",
    fullName: "Hypertext Transfer Protocol / Hypertext Transfer Protocol Secure",
    layer: "Application Layer",
    transport: "TCP",
    ports: "80 / 443",
    purpose: "Transfers web pages, API requests, and web resources",
    description:
      "HTTP is used by browsers and servers to exchange web content. HTTPS adds TLS encryption to protect communication.",
    useCases: ["Websites", "REST APIs", "Web applications"],
    example: "Browser requests https://example.com and receives an HTTP response",
    image: "/images/http.svg",
  },
  {
    id: 2,
    slug: "dns",
    name: "DNS",
    fullName: "Domain Name System",
    layer: "Application Layer",
    transport: "Usually UDP, sometimes TCP",
    ports: "53",
    purpose: "Converts domain names into IP addresses",
    description:
      "DNS maps human-readable names such as example.com to IP addresses computers can use.",
    useCases: ["Website navigation", "Domain lookup", "Email routing", "Service discovery"],
    example: "example.com -> DNS lookup -> IP address",
    image: "/images/dns.svg",
  },
  {
    id: 3,
    slug: "tcp",
    name: "TCP",
    fullName: "Transmission Control Protocol",
    layer: "Transport Layer",
    transport: "TCP",
    ports: "Depends on the application",
    purpose: "Provides reliable, ordered communication",
    description:
      "TCP establishes a connection and provides reliable, ordered delivery with retransmission and flow control.",
    useCases: ["HTTP/HTTPS", "SSH", "Email", "File transfer"],
    example: "SYN -> SYN-ACK -> ACK three-way handshake",
    image: "/images/tcp.svg",
  },
  {
    id: 4,
    slug: "udp",
    name: "UDP",
    fullName: "User Datagram Protocol",
    layer: "Transport Layer",
    transport: "UDP",
    ports: "Depends on the application",
    purpose: "Sends data quickly without a reliable connection",
    description:
      "UDP sends datagrams without connection setup and does not guarantee delivery or ordering.",
    useCases: ["DNS", "Video streaming", "Voice calls", "Online games"],
    example: "Real-time audio may prefer new packets over retransmitting old lost packets",
    image: "/images/udp.svg",
  },
  {
    id: 5,
    slug: "dhcp",
    name: "DHCP",
    fullName: "Dynamic Host Configuration Protocol",
    layer: "Application Layer",
    transport: "UDP",
    ports: "67 / 68",
    purpose: "Automatically configures devices on a network",
    description:
      "DHCP provides settings such as IP address, subnet mask, default gateway, and DNS server.",
    useCases: ["Home Wi-Fi", "University networks", "Office networks", "Public Wi-Fi"],
    example: "Laptop joins Wi-Fi -> DHCP server assigns network settings",
    image: "/images/dhcp.svg",
  },
  {
    id: 6,
    slug: "tls",
    name: "TLS",
    fullName: "Transport Layer Security",
    layer: "Security protocol used above the transport layer",
    transport: "Commonly used with TCP",
    ports: "No single dedicated port; commonly used with HTTPS on 443",
    purpose: "Provides encryption, authentication, and integrity",
    description:
      "TLS protects application communication and is what makes HTTPS secure.",
    useCases: ["HTTPS websites", "Secure APIs", "Secure email connections"],
    example: "Browser and server perform a TLS handshake before encrypted communication",
    image: "/images/tls.svg",
  },
];

module.exports = protocols;
